name: doxygen

on:
  push:
    branches:
      - main

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen
        run: doxygen Doxyfile

      - name: Deploy Doxygen
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
